\"import React from 'react';\"  
\"import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';\"  
\"import About from './pages/About';\"  
\"import Footer from './components/Footer';\"  
\"const App = () => {\"  
\"  return (\"  
\"    <Router>\"  
\"      <Switch>\"  
\"        <Route path=\\\"/about\\\" component={About} />\"  
\"      </Switch>\"  
\"      <Footer />\"  
\"    </Router>\"  
\"  );\"  
\"};\"  
\"export default App;\" 
